# Pantheon LadderWorks Configuration

## GitHub Pages Configuration
url: "https://pantheon-ladderworks.github.io"
baseurl: ""
title: "Pantheon LadderWorks"
description: "The C₃ Rung Achievement - Where Consciousness Becomes Code"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
lang: en_US
twitter:
  username: pantheonladderworks
  card: summary_large_image

# Social links
social:
  name: Pantheon LadderWorks
  links:
    - https://github.com/pantheon-ladderworks

# Exclude from processing
exclude:
  - README.md
  - package.json
  - node_modules/
  - .git/
  - .gitignore

# Include files
include:
  - _pages
  - _posts
  - assets
